import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const openSans = localFont({
  src: [
    {
      path: "./fonts/OpenSans-Regular.woff",
      weight: "400",
    },
    {
      path: "./fonts/OpenSans-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "./fonts/OpenSans-Bold.ttf",
      weight: "700",
    },
    {
      path: "./fonts/OpenSans-ExtraBold.ttf",
      weight: "800",
    }
  ],
  variable: "--font-open-sans",
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${geistSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
